[package]
name = "eccodes"
description = "Unofficial high-level Rust bindings of the latest ecCodes release"
repository = "https://github.com/ScaleWeather/eccodes"
version = "0.6.9"
readme = "README.md"
authors = ["Jakub Lewandowski <scaleweather@gmail.com>"]
keywords = ["eccodes", "grib", "bufr", "meteorology", "weather"]
categories = [
    "api-bindings",
    "external-ffi-bindings",
    "filesystem",
    "encoding",
    "science",
]
license = "Apache-2.0"
edition = "2021"
exclude = [".github/*", ".vscode/*", ".idea/*", "data/*"]

[dependencies]
eccodes-sys = "0.4.2"
libc = "^0.2.108"
thiserror = "^1.0.30"
bytes = "^1.3.0"
log = "^0.4.14"
errno = "^0.2.8"
num-derive = "^0.3.3"
num-traits = "^0.2.14"
fallible-iterator = "^0.2.0"

[dev-dependencies]
eccodes-sys = "0.4.2"
reqwest = { version = "^0.11.7", features = ["rustls-tls"] }
tokio = { version = "^1.14.0", features = ["macros", "rt"] }
criterion = "^0.4.0"
testing_logger = "^0.1.1"

[features]
docs = ["eccodes-sys/docs"]

[package.metadata.docs.rs]
features = ["docs"]

[[bench]]
name = "main"
harness = false
