[package]
name = "eccodes"
description = "Unofficial high-level Rust bindings of the latest ecCodes release"
repository = "https://github.com/ScaleWeather/eccodes"
version = "0.0.1"
readme = "README.md"
authors = ["Jakub Lewandowski <scaleweather@gmail.com>"]
keywords = ["eccodes", "grib", "bufr", "meteorology", "weather"]
categories = [
    "api-bindings",
    "external-ffi-bindings",
    "mathematics",
    "encoding",
    "science",
]
license = "Apache-2.0"
edition = "2018"
exclude = [".github/*"]

[dependencies]
eccodes-sys = "0.1.2"
libc = "0.2.97"
