[package]
name = "eccodes"
description = "Unofficial high-level Rust bindings of the latest ecCodes release"
repository = "https://github.com/ScaleWeather/eccodes"
version = "0.5.4"
readme = "README.md"
authors = ["Jakub Lewandowski <scaleweather@gmail.com>"]
keywords = ["eccodes", "grib", "bufr", "meteorology", "weather"]
categories = [
    "api-bindings",
    "external-ffi-bindings",
    "mathematics",
    "encoding",
    "science",
]
license = "Apache-2.0"
edition = "2021"
exclude = [".github/*", ".vscode/*", ".idea/*", "data/*"]

[dependencies]
eccodes-sys = "0.2.2"
libc = "0.2.106"
thiserror = "1.0.30"
bytes = "1.1.0"
log = "0.4.14"
errno = "0.2.8"
num-derive = "0.3.3"
num-traits = "0.2.14"
fallible-iterator = "0.2.0"

[dev-dependencies]
eccodes-sys = "0.2.2"
reqwest = { version = "0.11.6", features = ["rustls-tls"] }
tokio = { version = "1.13.0", features = ["macros", "rt"] }
criterion = "0.3.5"
testing_logger = "0.1.1"

[features]
docs = ["eccodes-sys/docs"]

[package.metadata.docs.rs]
features = ["docs"]

[[bench]]
name = "main"
harness = false
